### ISSUE TITLE
请问能不能加入弹幕功能

### ISSUE THREAD

**Issue by LovelyXy** [dxhuii/react-5ddm#2]

**Comment by dxhuii** [comment]
这个本来是加在播放器上的，后来没什么发，还有，站小，也没有时间审核弹幕，最后就直接去掉了， dplayer播放器，是有弹幕功能的。
[http://dplayer.js.org/zh/guide.html#弹幕](http://dplayer.js.org/zh/guide.html#%E5%BC%B9%E5%B9%95)
